version: "3"

services:
  web:
    build: .
    command:
      - sh
      - -c
      - |
        python manage.py migrate
        daphne -b 0.0.0.0 -p 80 website.asgi:application
    volumes:
      - .:/code
    ports:
      - 80:80