version: "3"

services:
  web:
    build: .
    command:
      - sh
      - -c
      - |
        python manage.py migrate
        daphne -b 0.0.0.0 website.asgi:application
    volumes:
      - .:/code
    ports:
      - 8000:8000