# Generated by Django 3.2.7 on 2021-10-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MRCResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('question_text', models.CharField(max_length=300)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('answer_text', models.CharField(max_length=512)),
            ],
        ),
    ]
