# Generated by Django 3.2.7 on 2021-10-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrcresults',
            name='question_text',
            field=models.CharField(max_length=300, verbose_name='Question: '),
        ),
    ]
