# Generated by Django 3.2.7 on 2021-11-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrc', '0004_alter_mrcresults_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrcresults',
            name='date_time',
        ),
    ]
