# Generated by Django 3.2.7 on 2021-11-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrc', '0006_mrcresults_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrcresults',
            name='date_time',
        ),
    ]
