# Generated by Django 3.2.7 on 2021-11-04 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrc', '0008_auto_20211104_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrcresults',
            name='answer_text',
            field=models.CharField(default='fhs', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrcresults',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 12, 16, 17, 164572)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrcresults',
            name='topic',
            field=models.CharField(default='gdfg', max_length=30),
            preserve_default=False,
        ),
    ]
