# Generated by Django 3.2.7 on 2021-11-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrc', '0011_auto_20211107_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MRCResults',
        ),
    ]
