# Generated by Django 3.2.7 on 2021-11-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrc', '0013_mrcresults_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrcresults',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrc.topic', to_field='topic'),
        ),
    ]
