# Generated by Django 3.2.7 on 2021-11-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrc', '0015_topic_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrcresults',
            name='question_text',
            field=models.CharField(max_length=300),
        ),
    ]
