# Generated by Django 3.2.7 on 2021-11-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrc', '0016_alter_mrcresults_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default='fdfs', max_length=256),
            preserve_default=False,
        ),
    ]
