# Generated by Django 3.2.7 on 2021-11-01 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrc', '0002_alter_mrcresults_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrcresults',
            name='date',
        ),
        migrations.AddField(
            model_name='mrcresults',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 15, 41, 52, 751741), verbose_name='Date and Time'),
            preserve_default=False,
        ),
    ]
