# Generated by Django 3.2.7 on 2021-11-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrc', '0003_auto_20211101_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrcresults',
            name='question_text',
            field=models.CharField(max_length=300, verbose_name='Question'),
        ),
    ]
