# Generated by Django 3.2.7 on 2021-11-01 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrc', '0005_remove_mrcresults_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrcresults',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 20, 40, 40, 857642)),
            preserve_default=False,
        ),
    ]
