# Generated by Django 3.2.7 on 2021-11-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrc', '0009_auto_20211104_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mrcresults',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrc.topic', to_field='topic'),
        ),
    ]
