# Generated by Django 3.2.7 on 2021-11-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrc', '0010_auto_20211107_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrcresults',
            name='topic',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
