# Generated by Django 3.2.7 on 2021-11-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mrc', '0012_delete_mrcresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRCResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('question_text', models.CharField(max_length=300, verbose_name='Question')),
                ('date_time', models.DateTimeField()),
                ('answer_text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
